language: node_js

node_js:
  - 0.10

before_script:
  - npm install -g grunt-cli

script:
  - npm install
  - bower install
  - grunt test

deploy:
  provider: heroku
  all_branches: true
  skip_cleanup: true
  api_key:
    secure: C3yZ7lh8J0IdamDUc7pY5nmf8gRlNHNRz60E/pSL+ksDTbGWPw5wD+Mq5wohV/QdLktjyAGVQh3hJP/Y2CvXrznj+cK+lePXK0yTnJK4D9sOepQBVrxStA4ZjIdZ7fIvKy3E3jVxPd9Hp3sJZGLU8OhaYsLFgtnnkrW9d2kaY3M=
  app: node-snapshot
  on:
    repo: Wildhoney/Snapshot.js
